#Root premission required by travis
sudo: required
#Service command will install docker
services:
  - docker
#Before installing, the next line tags the container id and renames it
before_install:
  - docker build -t kiwiman/docker-react -f Dockerfile.dev .

#The below command ensures that npm test end when it has been completed
script:
  - docker run kiwiman/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker_react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-467777605727"
  buket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
